[AccessTransformers]

; Expose the Customization Material mapping array so we can do CDO injection
BlueprintReadWrite=(Class="/Script/FactoryGame.FGFactoryCustomizationDescriptor_Material", Property="mBuildableMap")

; Expose schematic unlock array to inject pine into 1-1
BlueprintReadWrite=(Class="/Script/FactoryGame.FGSchematic", Property="mUnlocks")

; Expose the schematics array inside schematic unlocks to inject custom wood CBGs
BlueprintReadWrite=(Class="/Script/FactoryGame.FGUnlockSchematic", Property="mSchematics")

; Expose Ingredients array in Customization Recipes for Build Cost Session Setting Handling 
BlueprintReadWrite=(Class="/Script/FactoryGame.FGRecipe", Property="mIngredients")
